<?php

namespace AppBundle\Repository;

/**
 * CurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CurrencyRepository extends \Doctrine\ORM\EntityRepository
{
    public function getFlatSymbols()
    {
        $qb = $this->createQueryBuilder("c")
            ->select("c.symbol")
        ;

        $data = $qb->getQuery()->getScalarResult();
        $symbols = array_column($data, "symbol");

        return $symbols;
    }
}
