<?php

namespace AppBundle\Repository;

/**
 * GlobalBalanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GlobalBalanceRepository extends \Doctrine\ORM\EntityRepository
{
}
