<?php

namespace AppBundle\Repository;

/**
 * MarketPairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketPairRepository extends \Doctrine\ORM\EntityRepository
{
}
