<?php

namespace AppBundle\Repository;

use AppBundle\Entity\MarketPair;
use AppBundle\Entity\Pair;

/**
 * MarketPairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MarketPairRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Pair $pair
     * @return MarketPair[]
     */
    public function fetchActiveMarketPairs(Pair $pair)
    {
        $qb = $this->createQueryBuilder('mp')
            ->join('AppBundle\Entity\Market', 'm', 'WITH', 'mp.market = m')
            ->where('m.enabled = true')
            ->andWhere('mp.pair = :pair')
            ->setParameter('pair', $pair)
        ;

        return $qb->getQuery()->getResult();
    }
}
