<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Market;

/**
 * PairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PairRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Market $market
     * @return array
     */
    public function fetchPairsByMarket(Market $market)
    {
        $qb = $this->createQueryBuilder("p")
            ->join('AppBundle\Entity\MarketPair', 'mp', 'WITH', 'mp.pair = p')
            ->where('mp.market = :market')
            ->setParameter('market', $market)
        ;

        return $qb->getQuery()->getResult();
    }

    /**
     * @return array
     */
    public function fetchParsable()
    {
        $qb = $this->createQueryBuilder("p")
            ->join('AppBundle\Entity\Currency', 'c1', 'WITH', 'c1 = p.sourceCurrency')
            ->join('AppBundle\Entity\Currency', 'c2', 'WITH', 'c2 = p.targetCurrency')
            ->where('c1.parsable = true OR c2.parsable = true')
        ;

        return $qb->getQuery()->getResult();
    }
}
