<?php

namespace AppBundle\Repository;

/**
 * TickerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TickerRepository extends \Doctrine\ORM\EntityRepository
{
}
