<?php

namespace AppBundle\Repository;
use AppBundle\Entity\Ticker;

/**
 * TickerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TickerRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Ticker $ticker
     * @return mixed
     */
    public function getPreviousTicker(Ticker $ticker)
    {
        $qb = $this->createQueryBuilder("t")
            ->andWhere("t.market = :market")
            ->andWhere("t.pair = :pair")
            ->setParameter("market", $ticker->getMarket())
            ->setParameter("pair", $ticker->getPair())
            ->orderBy("t.createdAt", "DESC")
            ->setMaxResults(1)
        ;

        return $qb->getQuery()->getOneOrNullResult();
    }
}
