services:
    app.market.api_client.collection:
        class: AppBundle\Service\Market\ApiClient\ApiClientCollection

    app.market.api_client.bitstamp:
        class: AppBundle\Service\Market\ApiClient\BitstampClient

    app.market.api_client.btce:
        class: AppBundle\Service\Market\ApiClient\BtceClient
        arguments:
            - { key: "%api.clients.btce.key%", secret: "%api.clients.btce.secret%" }
        tags:
            - { name: app.api_client, alias: btc-e }

    app.market.api_client.kraken:
        class: AppBundle\Service\Market\ApiClient\KrakenClient


    app.ticker.manager:
        class: AppBundle\Service\Ticker\TickerManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.market.api_client.collection"

    app.balance.manager:
        class: AppBundle\Service\Balance\BalanceManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.market.api_client.collection"