services:
    app.market.api_client.bitstamp:
        class: AppBundle\Service\Market\ApiClient\BitstampClient

    app.market.api_client.btce:
        class: AppBundle\Service\Market\ApiClient\BtceClient
        arguments:
            - [key: "%api.clients.btce.key%", secret: "%api.clients.btce.secret%"]

    app.market.api_client.kraken:
        class: AppBundle\Service\Market\ApiClient\KrakenClient


    app.ticker.manager:
        class: AppBundle\Service\Ticker\TickerManager
        arguments:
            - "@doctrine.orm.entity_manager"

    app.balance.manager:
        class: AppBundle\Service\Balance\BalanceManager
        arguments:
            - "@doctrine.orm.entity_manager"