services:
    app.market.api_client.ticker.collection:
        class: AppBundle\Service\Market\ApiClient\TickerApiClientCollection

    app.market.api_client.balance.collection:
        class: AppBundle\Service\Market\ApiClient\BalanceApiClientCollection

    app.market.api_client.volume.collection:
        class: AppBundle\Service\Market\ApiClient\VolumeApiClientCollection

    app.market.api_client.bitstamp:
        class: AppBundle\Service\Market\ApiClient\BitstampClient
        tags:
            - { name: app.api_client.ticker, alias: bitstamp }

    app.market.api_client.btce:
        class: AppBundle\Service\Market\ApiClient\BtceClient
        arguments:
            - { key: "%api.clients.btce.key%", secret: "%api.clients.btce.secret%" }
        tags:
            - { name: app.api_client.ticker, alias: btc-e }
            - { name: app.api_client.balance, alias: btc-e }

    app.market.api_client.bittrex:
        class: AppBundle\Service\Market\ApiClient\BittrexClient
        arguments:
            - { key: "%api.clients.bittrex.key%", secret: "%api.clients.bittrex.secret%" }
        tags:
            - { name: app.api_client.ticker, alias: bittrex }
            - { name: app.api_client.volume, alias: bittrex }

    app.market.api_client.kraken:
        class: AppBundle\Service\Market\ApiClient\KrakenClient
        tags:
            - { name: app.api_client.ticker, alias: kraken }

    app.market.api_client.xbtce:
        class: AppBundle\Service\Market\ApiClient\XbtceClient
        tags:
            - { name: app.api_client.ticker, alias: xbtce }

    app.market.api_client.coinbase:
        class: AppBundle\Service\Market\ApiClient\CoinbaseClient
        arguments:
            - { key: "%api.clients.coinbase.key%", secret: "%api.clients.coinbase.secret%" }
        tags:
            - { name: app.api_client.ticker, alias: coinbase }
            - { name: app.api_client.balance, alias: coinbase }

    app.ticker.manager:
        class: AppBundle\Service\Ticker\TickerManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.market.api_client.ticker.collection"

    app.balance.manager:
        class: AppBundle\Service\Balance\BalanceManager
        arguments:
            - "@doctrine.orm.entity_manager"
            - "@app.market.api_client.balance.collection"

    app.form.market:
        class: AppBundle\Form\MarketType
        arguments:
            - "@doctrine.orm.entity_manager"
        tags:
            - { name: form.type }